/********************************************************
* Lab 3 Programming Assignment - Communicating Processes
* @authors: Nathan Lentz & Brandon Attala
* @date: February 2nd, 2-17
* 
* Practice with Signal Handlers and demonstrates 
* communication between a parent process and its child
********************************************************/

#include <stdio.h>
#include <string.h>
#include <unistd.h>
#include <stdlib.h>
#include <time.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <signal.h>


/* Prototypes */

void signal_handler();


/* Main Method */

int main()
{

	
	srand(time(NULL));

	pid_t pid;
	int rNum;
	int status;

	if((pid = fork()) < 0){
		perror("Failed to fork");
		exit(1);
	}	

	// Child Instructions
	else if(pid == 0){
		printf("Spawned child PID#: %d\n", getpid());

		while(1){
			// Wait random amount of time (1-5 seconds)
			rNum = (rand() % 5) + 1;

			// Randomly send signal to parent
		}


		
		
	

		


	}
	// Parent Instructions
	else{

		// Register signal handler with user signals
		signal(SIGUSR1, signal_handler);
		signal(SIGUSR2, signal_handler);
		printf("waiting. . .");
		wait(&status);

	}




	return 0;
}

/*******************************************************
* Signal Handler generates outpu that is dependant on 
* the signal which was generated by user defined signals
* SIGUSR1 / SIGUSR2
********************************************************/

void signal_handler(int signal)
{
	//TODO: Do stuff for received signal
	if(signal == SIGUSR1){

	}

	else if(signal == SIGNUSR2){

	}
}