/********************************************************
* Lab 3 Programming Assignment - Communicating Processes
* @authors: Nathan Lentz & Brandon Attala
* @date: February 2nd, 2-17
* 
* Practice with Signal Handlers and demonstrates 
* communication between a parent process and its child
********************************************************/

#include <stdio.h>
#include <string.h>
#include <unistd.h>
#include <stdlib.h>
#include <time.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <signal.h>


/* Prototypes */

void signalHandler(int signal);

/* Global Variables */

pid_t pid;


/* Main Method */

int main()
{

	
	srand(time(NULL));

	int status;

	if((pid = fork()) < 0){
		perror("Failed to fork");
		exit(1);
	}	

	// Child Instructions
	else if(pid == 0){
		printf("Spawned child PID#: %d\n", getpid());

		pid_t ppid = getppid();

		while(1){
			int randomNumber;
			int randomSignal;
			// Wait random amount of time (1-5 seconds)
			randomNumber = (rand() % 5) + 1;
			sleep(randomNumber);

			// Randomly send signal to parent
			randomSignal = rand() % 2;
			if(randomSignal == 0){
				kill(ppid,SIGUSR1);
			}
			else{
				kill(ppid,SIGUSR2);
			}
		}
	}
	// Parent Instructions
	else{

		// Register signal handler with user signals
		signal(SIGUSR1, signalHandler);
		signal(SIGUSR2, signalHandler);
		signal(SIGINT, signalHandler);
		printf("Waiting. . .");
		wait(&status);

	}
	return 0;
}

/*******************************************************
* Signal Handler generates outpu that is dependant on 
* the signal which was generated by user defined signals
* SIGUSR1 / SIGUSR2
********************************************************/

void signalHandler(int signal)
{
	
	if(signal == SIGUSR1){
		printf("\t\t Received SIGUSR1\n");
		printf("Waiting . . .");
	}

	else if(signal == SIGUSR2){
		printf("\t\t Received SIGUSR2\n");
		printf("Waiting . . .");
	}

	else {
		printf("\t\tStupid kids, killing the child\n");
		kill(SIGKILL, pid);

		printf("I think I am the parent: %d", getpid());
		exit(0);
	}
}
